# config.yaml
environment:
  name: FrozenLake-v1
  is_slippery: True
  map_name: 4x4
  reward_schedule: [1, -1, -0.01] # Goal, hole, normal move


agent:
  learning_rate: 0.001
  batch_size: 64
  buffer_size: 10000
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  target_update_freq: 1000

training:
  episodes: 200
  gammas: [0.1, 0.99]
  device: cpu
